### ISSUE TITLE
Print Specific Error Message

### ISSUE THREAD

**Issue by Danny-awesome** [evanshortiss/express-joi-validation#13]
Hello. I'm just using express-joi-validation for the first time... Using Joi itself is fine by me since I get to bring out just specific error message, but I can't seem to do that with this. It gives all error messages if it checks off true with validations of request.

**Comment by evanshortiss** [comment]
@Danny-awesome, could you provide an example of the issue with the output you expect vs. output you want?

It *sounds* to me like you want to set the `abortEarly` option to `true`? You can read about that option  [here](https://github.com/hapijs/joi/blob/v14.3.1/API.md#validatevalue-schema-options-callback).

`express-joi-validation` sets this option to `false` by default as seen [here](https://github.com/evanshortiss/express-joi-validation/blob/master/express-joi-validation.js#L10).

Does this help?

**Comment by evanshortiss** [comment]
I should mention to set it you can do it like so:

```
const validator = require('express-joi-validation')({});

const joiOpts = { abortEarly: true }

const body = validator.body(SCHEMA, { joi: joiOpts  })
```

**Comment by Danny-awesome** [comment]
thanks. i skipped the abortEarly option.
that clears a lot. really helpful.
the documentation states other joi options but could help me out with a
short description on them?

**Comment by Danny-awesome** [comment]
Also
// error handler
app.use((err, req, res, next) => {
if (err.error.isJoi) {
res.status(400).json({
type: err.body, //should i use different error handler depending on type
like params,body,query or
//specify all in here?. Also does this look well-written?
message: err.error.toString()
});
} else {
next(err);
}
});

**Comment by Danny-awesome** [comment]
--user-validations.js
const custNameSchema = Joi.object({
name: Joi.string().required().min(4)
});
const custPhoneSchema = Joi.object({
phone: Joi.string().required().min(6)
});

---user.js
const validator = require('express-joi-validation')({ passError: true });
const validators = require('../joi-validators/customer-validators');
router.post('/',validator.body(validators.custNameSchema,
{ joi: joiOpts}), validator.body(validators.custPhoneSchema,
{ joi: joiOpts}) );

error ->
{ "message": "ValidationError: \"phone\" is not allowed" }

can't i use to the same requests inputs like that?

**Comment by evanshortiss** [comment]
@Danny-awesome 

> the documentation states other joi options but could help me out with a
short description on them

Joi details all of it's options in its API documentation. Best look there - https://github.com/hapijs/joi/blob/master/API.md

> should i use different error handler depending on type

It's up to you. In general you can probably use the same function, just make sure to specify the type in whatever response you return so it's clear that the "query" was wrong or the "body".

**Comment by Danny-awesome** [comment]
thanks. you answered my question. All's clear to me now.

**Comment by evanshortiss** [comment]
Happy to help. Have a great weekend 😄
