### ISSUE TITLE
Wrong typing: Type 'ValidationResult' is not generic

### ISSUE THREAD

**Issue by zirpsmaximilian** [evanshortiss/express-joi-validation#24]
Versions:
```json
{
"@hapi/joi": "^16.1.7",
"@types/hapi__joi": "^16.0.2",
"express-joi-validation": "^4.0.1",
"typescript": "3.6.4",
}
```

Error occurs in `express-joi-validation.d.ts` on line 27:
```typescript
export interface ExpressJoiError extends Joi.ValidationResult<any> {
  type: ContainerTypes
}
```

Errormessage: _Type 'ValidationResult' is not generic_

**hapi__joi/index.d.ts**
```typescript
    interface ValidationResult {
        error: ValidationError;
        errors: ValidationError;
        warning: ValidationError;
        value: any;
    }
```

**Comment by evanshortiss** [comment]
@zirpsmaximilian see this thread - https://github.com/DefinitelyTyped/DefinitelyTyped/pull/38361#discussion_r327484202

Can you use `@hapi/joi` version 15 and `@types/hapi__joi` version 15 until I get a response to that thread? I don't want to change this module if `@types/hapi__joi` can be changed instead.

**Comment by zirpsmaximilian** [comment]
> @zirpsmaximilian see this thread - [DefinitelyTyped/DefinitelyTyped#38361 (comment)](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/38361#discussion_r327484202)
> 
> Can you use `@hapi/joi` version 15 and `@types/hapi__joi` version 15 until I get a response to that thread? I don't want to change this module if `@types/hapi__joi` can be changed instead.

Thanks, that worked for me :)

**Comment by evanshortiss** [comment]
Great! I might need to change this module to conform with types for v16 since they removed a useful generic. Will leave this issue open to track it.
