### ISSUE TITLE
 Type 'Request<ParamsDictionary, any, any>' is not assignable to type 'ValidatedRequest<RequestSchema>'

### ISSUE THREAD

**Issue by escobar5** [evanshortiss/express-joi-validation#28]
I'm having problems when validating params with a required param, the error I get is:

> Argument of type '(req: ValidatedRequest<RequestSchema>, res: Response) => Promise<void>' is not assignable to parameter of type 'RequestHandler'.
  Types of parameters 'req' and 'req' are incompatible.
    Type 'Request<ParamsDictionary, any, any>' is not assignable to type 'ValidatedRequest<RequestSchema>'.
      Types of property 'params' are incompatible.
        Property 'uuid' is missing in type 'ParamsDictionary' but required in type 'Map<{} & { uuid: string; }>'

This is the code:

```
const validator = createValidator({ passError: true });
const paramsSchema = Joi.object({
  uuid: Joi.string().required()
});

interface RequestSchema extends ValidatedRequestSchema {
  [ContainerTypes.Params]: Joi.extractType<typeof paramsSchema>
}

router.get('/:uuid', 
  validator.params(paramsSchema), 
  asyncHandler(async(req: ValidatedRequest<RequestSchema>, res: Response) => {
     ...
  })
);
```

**Comment by escobar5** [comment]
This was my fault, my `asyncHandler` middleware expected type `RequestHandler`, after I changed the expected type in my middleware it worked.

**Comment by denesh-r** [comment]
@escobar5 Can you please explain how you fixed it? 
I am using express-async-handler and running into the same problem.

**Comment by domsen123** [comment]
@escobar5 Can you please explain how you fixed it? Same error here!
