### ISSUE TITLE
Accept global validations options

### ISSUE THREAD

**Issue by scucchiero** [evanshortiss/express-joi-validation#31]
Are you accepting PRs? Which branch should I branch from?

I want to add the option to override the container default options.

**Comment by scucchiero** [comment]
https://github.com/evanshortiss/express-joi-validation/pull/32

**Comment by evanshortiss** [comment]
Thanks @scucchiero, will release as 5.x to avoid unexpected changes for people, since it changes the behavior people expect with `opts.joi`
