### ISSUE TITLE
在使用tsc编译的时候提示错误

### ISSUE THREAD

**Issue by wenwst** [evanshortiss/express-joi-validation#38]
> [ 8/10] RUN ./node_modules/.bin/tsc:                                                                                                                                                                                  
#12 16.58 node_modules/express-joi-validation/express-joi-validation.d.ts(28,42): error TS2312: An interface can only extend an object type or intersection of object types with statically known members.

**Comment by rrnara** [comment]
Created a pull request to fix this: https://github.com/evanshortiss/express-joi-validation/pull/39

Hope someone can merge & release a new version

**Comment by evanshortiss** [comment]
Thanks @wenwst @rrnara. Will merge that PR later today.

**Comment by alexandrryazanov** [comment]
@evanshortiss Merge it pls

**Comment by evanshortiss** [comment]
Published.

**Comment by evanshortiss** [comment]
@alexandrryazanov in the future you can `npm install rrnara/express-joi-validation` (or whatever username) while waiting on merges.

Apologies for the delay folks.
