### ISSUE TITLE
Response handling

### ISSUE THREAD

**Issue by maikelmclauflin** [evanshortiss/express-joi-validation#7]
Hi there, is it possible to do response handling? or is it best to just do this by validating directly on the object that is being sent back?

**Comment by evanshortiss** [comment]
By default the module will return a 400 response on validation errors as explained [here](https://github.com/evanshortiss/express-joi-validation#error-handling)

You can also set `passError` to true when initialising the middleware if you'd prefer to handle validation errors and response sending/formatting in you express error handler as shown [here](https://github.com/evanshortiss/express-joi-validation#custom-express-error-handler)

@maikelmclauflin does this answer your issue? If not, could you provide a little more detail on the issue?

**Comment by maikelmclauflin** [comment]
Oh, no, like validating the response object that gets sent back to the client. So if the client is expecting the json to look like 
```
{ "one": 1 }
```
is there a middleware to check this before it goes out. I've looked over the docs a couple of times now, and it seems that there is not. I'll see if I can submit something small.

**Comment by evanshortiss** [comment]
@maikelmclauflin I understand now. Thanks for the update. 

Could you explain the rationale? If you are building the response why would you need to check it in this manner?

**Comment by maikelmclauflin** [comment]
Well, mainly to exist as proof of structure. 

Sometimes one isn't necessarily building the response per se. One may be passing it from another endpoint, or pulling directly from a database which, in addition, may hold sensitive data or may not exist in the same structure.

In addition, it helps instill confidence in the expectation of the result on the client's side.

For instance, if someone finds they are getting a response back that they do not think they should be getting, they would be able to check the validation even if the individual who built it is no longer around.

This is just so that Joi and handling does not have to exist in the handler of every endpoint but can exist at a layer above, where the routes are connected to middlewares and the response validation middleware can exist by itself. At least more easily.

Thanks for considering the request 😄
